baseURL = 'https://theeverythingjournal.netlify.app'
languageCode = 'en-us'
title = 'The Everything Journal'
theme = 'quint'

# Pagination - Move 'paginate' to the top level
paginate = 4  # This is the correct way to set the number of posts per page

[params]
css = ["css/custom.css"]
numImages = 30
useToc = true

contact = "You can write me an [email](mailto:me)."

[[params.social]]
    url = "https://github.com/lyskh"
    icon = "/social/github.svg"
    name = "GitHub"
