baseURL = 'https://theeverythingjournal.netlify.app'
languageCode = 'en-us'
title = 'The Everything Journal'
description = 'a blog about everything by lyskhea'
author = 'lyskhea'
theme = 'quint'
enableRobotsTXT = true
canonifyURLs = true


# Pagination - Move 'paginate' to the top level
paginate = 4  # This is the correct way to set the number of posts per page
[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[permalinks]
  posts = "/:slug/"

[minify]
  disableXML = true
  minifyOutput = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100

[[related.indices]]
  name = "categories"
  weight = 80

[params]
disableKinds = ["taxonomy", "term"] # Make sure "robotsTXT" is NOT listed here
css = ["css/custom.css"]
numImages = 30
useToc = true

contact = "You can write me an [email](mailto:me)."

[[params.social]]
    url = "https://github.com/lyskh"
    icon = "/social/github.svg"
    name = "GitHub"
