baseURL = 'https://theeverythingjournal.netlify.app'
languageCode = 'en-us'
title = 'The Everything Journal'
theme = 'quint'
# Theme config. Your config (yoursite/hugo.toml) overrides this one.

[pagination]
  pagerSize = 10                        # Number of posts to show on a list page
summaryLength = 20                  # Number of characters in your card summaries

[params]
css = ["css/custom.css"]            # Your custom CSS overrides, stored in yoursite/static/
numImages = 10                      # Number of random images to choose from for banners (in themes/quint/static/images)
useToc = false                      # Set to true to show a Table of Contents on multi-heading posts

contact = "You can write me an [email](mailto:me)."

# [[params.social]]                 # Customize your social links below!
#     url = "https://github.com/lyskh"
#     icon = "/social/github.svg"
#     name = "GitHub"

[[params.social]]
    url = "https://github.com/lyskh"
    icon = "/social/github.svg"
    name = "GitHub"

# [[params.social]]
#     url = "mailto:me"
#     icon = "/social/email.png"
#     name = "Email"

# [[params.social]]
#     url = "https://www.facebook.com/lyskhaer"
#     icon = "/social/instagram.svg"
#     name = "Facebook"
